<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.qa.automation.ndtv.weatherreporting.tests.WeatherReportingTests" tests="1" time="44.301" ignored="0" failures="1" timestamp="21 Sep 2020 19:55:59 GMT" skipped="0" hostname="LAPTOP-JOPOHLMU" errors="0">
  <testcase name="captureWeatherDetailsFromUIAndApi" time="44.301" classname="com.qa.automation.ndtv.weatherreporting.tests.WeatherReportingTests">
    <failure type="java.lang.AssertionError" message="Exception: Cause- AssertionError, null, Message- The following asserts failed:
	Failed to get valid response from API">
      <![CDATA[java.lang.AssertionError: Exception: Cause- AssertionError, null, Message- The following asserts failed:
	Failed to get valid response from API
	at org.testng.Assert.fail(Assert.java:94)
	at com.qa.automation.ndtv.weatherreporting.tests.WeatherReportingTests.captureWeatherDetailsFromUIAndApi(WeatherReportingTests.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- captureWeatherDetailsFromUIAndApi -->
</testsuite> <!-- com.qa.automation.ndtv.weatherreporting.tests.WeatherReportingTests -->
